[package]
name = "falso"
version = "0.0.1"
authors = ["Andreas Doerr"]
edition = "2018"

[dependencies]
sc-client-db = { git = "https://github.com/adoerr/substrate.git", branch = "master" }
sc-service = { git = "https://github.com/adoerr/substrate.git", branch = "master" }

substrate-test-runtime-client = { git = "https://github.com/adoerr/substrate.git", branch = "master" }
